steps:
  # BUILD SHELL
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'apps/shell'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/frontend-repo/shell:$_COMMIT_SHA',
        '.',
      ]

  # BUILD AUTH
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'apps/auth'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/frontend-repo/auth:$_COMMIT_SHA',
        '.',
      ]

  # BUILD DASHBOARD
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'apps/dashboard'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/frontend-repo/dashboard:$_COMMIT_SHA',
        '.',
      ]

  # PUSH ALL IMAGES
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/frontend-repo/shell:$_COMMIT_SHA',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/frontend-repo/auth:$_COMMIT_SHA',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/frontend-repo/dashboard:$_COMMIT_SHA',
      ]

  # KUBERNETES DEPLOY (KUSTOMIZE)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials my-gke-cluster \
          --region europe-west1 \
          --project $PROJECT_ID

        kubectl apply -k deploy/overlays/prod
