apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: auth

spec:
  replicas: 3

  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth
          image: app/auth:latest
          ports:
            - containerPort: 80

  strategy:
    canary:
      stableService: auth
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
