apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: preview-ingress

spec:
  rules:
    - host: pr.mycompany.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shell
                port:
                  number: 80
