apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: pr-${PR}

images:
  - name: app/shell
    newName: europe-west1-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REPOSITORY_NAME}/shell
    newTag: ${SHA}

  - name: app/auth
    newName: europe-west1-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REPOSITORY_NAME}/auth
    newTag: ${SHA}

  - name: app/dashboard
    newName: europe-west1-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REPOSITORY_NAME}/dashboard
    newTag: ${SHA}
