apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - secrets.yaml

namespace: dev

images:
  - name: app/shell
    newName: europe-west1-docker.pkg.dev/microfrontend-493002/mf-repo/shell
    newTag: dev
  - name: app/auth
    newName: europe-west1-docker.pkg.dev/microfrontend-493002/mf-repo/auth
    newTag: dev
  - name: app/dashboard
    newName: europe-west1-docker.pkg.dev/microfrontend-493002/mf-repo/dashboard
    newTag: dev

patches:
  - path: patches/shell.yaml
    target:
      kind: Deployment
      name: shell

  - path: patches/auth.yaml
    target:
      kind: Deployment
      name: auth

  - path: patches/dashboard.yaml
    target:
      kind: Deployment
      name: dashboard
